# docker-compose.yml(로컬용)

services:     # 컨테이너 지정

  web:
    container_name: web
    image: "${DOCKER_USERNAME}/web:${VERSION}"  # CI에서 빌드할 이미지 이름
    environment:
      DJANGO_SETTINGS_MODULE: golbang.settings
      REDIS_URL: redis://redis:6379/0  # Redis URL 환경 변수 설정
      REDIS_HOST: redis
    restart: always
    volumes:  # 파일 시스템 정의
      - .:/app
    ports:
      - "8000:8000"
    env_file: #
      - .env
      # - ./golbang_firebase_sdk.json # Firebase Admin SDK 키 파일

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports: # 포트포워딩 - 로컬의 호스트가 6379 포트를 사용 중일 수 있으므로 6379 포트를 도커 컨테이너의 6379 포트로 포워딩해줌
      - "6380:6379"
    volumes: # 파일 시스템 정의
      - redisdata:/data

  celery:   # celery 작업자
    container_name: celery
    image: "${DOCKER_USERNAME}/celery:${VERSION}"
    command: celery -A golbang worker -l info
    environment:
      DJANGO_SETTINGS_MODULE: golbang.settings
      REDIS_URL: redis://redis:6380/0
      REDIS_HOST: redis
    volumes:
      - .:/app
    env_file:
      - .env

  celery-beat:   # 주기적으로 업데이트
    container_name: celery-beat
    image: "${DOCKER_USERNAME}/celery-beat:${VERSION}"
    command: celery -A golbang beat -l info
    environment:
      DJANGO_SETTINGS_MODULE: golbang.settings
      REDIS_URL: redis://redis:6380/0
      REDIS_HOST: redis
    volumes:
      - .:/app
    env_file:
      - .env

volumes:
  redisdata: