name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Create .env file from SERVER_ENV_FILE secret
        run: |
          # SECRET_KEY에만 작은따옴표 추가
          echo "${{ secrets.SERVER_ENV_FILE }}" | sed 's/\r$//' | awk '
          /SECRET_KEY/ {
            print $1 "='\''" $2 "'\''"
          }
          !/SECRET_KEY/ {
            print
          }
          ' > .env
          echo "Generated .env file:"
          cat .env  # .env 파일 내용 출력 (보안 허용 시에만 사용)

      - name: Load environment variables from .env file
        run: |
          set -a
          source .env
          set +a
          echo "Loaded DOCKER_USERNAME: $DOCKER_USERNAME"  # 환경 변수 로드 확인

      - name: Log in to Docker Hub
        run: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

      - name: Build and push Docker image
        run: |
          docker-compose -f docker-compose.prod.yml build
          docker-compose -f docker-compose.prod.yml push
