name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set environment variables from SERVER_ENV_FILE
        run: |
          echo "${{ secrets.SERVER_ENV_FILE }}" | sed 's/\r$//' | while IFS= read -r line
          do
            export "$line"
          done

      - name: Verify environment variables
        run: |
          echo "DOCKER_USERNAME: $DOCKER_USERNAME"
          echo "DOCKER_PASSWORD length: ${#DOCKER_PASSWORD}"  # 비밀번호 길이만 출력

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: $DOCKER_USERNAME
          DOCKER_PASSWORD: $DOCKER_PASSWORD
        run: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

      - name: Build and push Docker image
        run: |
          docker-compose -f docker-compose.prod.yml build
          docker-compose -f docker-compose.prod.yml push
