name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Create .env file from secret
        run: echo "${{ secrets.SERVER_ENV_FILE }}" | sed 's/\r$//' > .env

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: $(grep -w 'DOCKER_USERNAME' .env | cut -d '=' -f2)
          DOCKER_PASSWORD: $(grep -w 'DOCKER_PASSWORD' .env | cut -d '=' -f2)
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build and push Docker image
        run: |
          docker-compose -f docker-compose.prod.yml build
          docker-compose -f docker-compose.prod.yml push

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull and run Docker container
        run: |
          docker pull <DOCKER_HUB_USERNAME>/<IMAGE_NAME>:latest
          docker-compose -f docker-compose.prod.yml up -d
