name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Create .env file from SERVER_ENV_FILE secret
        run: |
         echo "${{ secrets.SERVER_ENV_FILE }}" | sed 's/\r$//' | awk -F= '{print $1 "='\''" $2 "'\''"}' > .env
         echo "DOCKER_USERNAME=$DOCKER_USERNAME"  # 환경 변수 출력 확인 (보안상 실제 액세스 키는 출력되지 않도록 주의)
      - name: Load environment variables from .env file
        run: |
          set -a
          source .env
          set +a

      - name: Log in to Docker Hub
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build and push Docker image
        run: |
          docker-compose -f docker-compose.prod.yml build
          docker-compose -f docker-compose.prod.yml push

#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - name: Log in to Docker Hub
#        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
#
#      - name: Pull and run Docker container
#        run: |
#          docker pull <DOCKER_HUB_USERNAME>/<IMAGE_NAME>:latest
#          docker-compose -f docker-compose.prod.yml up -d
